[package]
name = "bios-chat-app"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
serde.workspace = true
bios-chat-basic = { path = "../chat-basic" }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
