=== Gateway


==== Directory Description

----
|spacegate
|-- res                             # spacegate resources
|-- src
|---- plugins
|------ auth.rs                     # auth-bios plugin
|-- Dockerfile                      # Dockerfile
----

==== How to use in k8s
see  https://github.com/ideaworld/spacegate/docs/k8s/installtion.md[spacegate doc]
but different:

==== Plugin
===== Auth
auth must have httproute below:
[source,yaml]
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: apis-test
spec:
  parentRefs:
  - name: gateway
  rules:
  - filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplaceFullPath
            replaceFullPath: /starsysApi/apis
    matches:
    - path:
        type: Exact
        value: /starsysApi/auth/auth/apis
      method: GET
    - path:
        type: Exact
        value: /starsysApi/apis
      method: POST

and auth config example:

[source,yaml]
apiVersion: spacegate.idealworld.group/v1
kind: SgFilter
metadata:
  name: auth-test
spec:
  filters:
    - code: auth
      config:
        auth_config: 
          fetch_server_config_path: /starsysApi/apis
        cache_url: "redis://127.0.0.1:6379"
  targetRefs:
    - kind: HTTPRoute
      name: iam-test
    - kind: HTTPRoute
      name: apis-test

===== Ip_Time

config example:

[source,yaml]
apiVersion: spacegate.idealworld.group/v1
kind: SgFilter
metadata:
  name: ip-time-filters
spec:
  filters:
    - code: ip_time
      config:
        rules:
          - ip_list:
              - "127.0.0.1"
              - "172.20.0.1"
            time_rule:
              mode: "black_list"
              ban:
                - start: "18:00:00"
                  end: "09:00:00"
  targetRefs:
    - kind: Gateway
      name: gateway