[package]
name = "bios-spi-stats"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_spi_stats"
path = "src/lib.rs"

[features]
default = ["spi-pg"]
spi-pg = ["tardis/reldb-postgres"]

[dependencies]
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default"] }
serde.workspace = true
lazy_static.workspace = true
itertools.workspace = true
tardis = { workspace = true, features = ["reldb-postgres", "web-server"] }
serde_json = { workspace = true, features = ["preserve_order"] }
strum = { workspace = true, features = ["derive"] }
bios-sdk-invoke = { version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
  "event","spi_log"
], default-features = false }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default", "test"] }
