[package]
name = "bios-example-framework-todo-list"
version = "0.1.0"
authors = ["gudaoxuri"]
homepage = "https://bios.idealworld.group/framework"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
derive_more = "0.99"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }

bios-framework = { path = "../../../framework", features = ["web_client", "reldb"] }
actix-web = { version = "3", default-features = false, features = ["compress"] }
validator = { version = "0.12", features = ["derive"] }
actix-web-validator = "2"

rbatis = { version = "2", default-features = false, features = ["tokio1", "mysql"] }

[dev-dependencies]
awc = { version = "2", features = ["rustls"] }
actix-rt = "1"
