[package]
name = "bios-example-framework-todo-list"
version = "0.1.0"
authors = ["gudaoxuri"]
homepage = "https://bios.idealworld.group/framework"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
derive_more = "^0"
log = "^0"
chrono = { version = "^0", features = ["serde"] }

bios-framework = { path = "../../../framework", features = ["web-client", "reldb"] }
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["compress-gzip", "rustls"] }
validator = { version = "^0", features = ["derive"] }
actix-web-validator = "^2"

sea-query = { version = "^0", default-features = false, features = ["derive", "backend-mysql", "sqlx-mysql", "with-chrono", "with-rust_decimal"] }
sqlx = { version = "^0", default-features = false, features = ["macros", "mysql", "chrono", "decimal", "runtime-tokio-native-tls"] }

[dev-dependencies]
awc = { version = "3.0.0-beta.7", features = ["rustls"] }
actix-rt = "^2"
