[package]
name = "iam"
version = "0.1.0"
authors = ["gudaoxuri <i@sunisle.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bios-framework = { path = "../../../framework" }
