FROM alpine:3.13 AS etcd-stage

ARG ETCD_VERSION="3.5.7"

WORKDIR /tmp

RUN wget https://github.com/etcd-io/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz \
    && tar -zxvf etcd-v${ETCD_VERSION}-linux-amd64.tar.gz \
    && mv etcd-v${ETCD_VERSION}-linux-amd64 etcd

FROM apache/apisix:2.15.0-alpine

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=etcd-stage /tmp/etcd/etcd /usr/bin/etcd
COPY --from=etcd-stage /tmp/etcd/etcdctl /usr/bin/etcdctl

COPY apisix/apisix/plugins/auth-bios.lua /usr/local/apisix/apisix/plugins/auth-bios.lua
COPY test/conf/apisix/config.yaml /usr/local/apisix/conf/config.yaml

VOLUME /usr/local/apisix/conf
VOLUME /etcd_data

EXPOSE 9080 9443 2379 2380

CMD ["sh", "-c", "(nohup etcd --data-dir=/etcd_data --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://localhost:2379 >/tmp/etcd.log 2>&1 &) && sleep 10 && /usr/bin/apisix init && /usr/bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"]

STOPSIGNAL SIGQUIT