[package]
name = "bios-chat-basic"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[lib]
name = "bios_chat_basic"
path = "src/lib.rs"

[dependencies]
serde.workspace = true
tardis = { workspace = true }
bios-basic = { path = "../../../basic", features = ["sdk"] }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
