[package]
name = "auth-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
bios-auth={ path = "../../../auth" }
tardis = { version = "0.1.0-alpha33", features = [
    "web-server",
] }