[package]
name = "bios-com-iam"
version = "0.1.0"
authors = ["gudaoxuri <i@sunisle.org>"]
homepage = "https://bios.idealworld.group"
documentation = "https://bios.idealworld.group"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2021"
readme = "README.adoc"
publish = false

[profile.release]
lto = true
codegen-units = 1

[lib]
name = "bios_com_iam"
path = "src/lib.rs"

[features]
sdk = ["tardis/web-client"]
kernel = ["tardis/reldb", "tardis/cache", "tardis/mq", "tardis/web-client", "sea-orm"]
service = ["kernel", "tardis/web-server", "poem-openapi"]
test = ["tardis/test"]

[dependencies]
bios-basic = { path = "../../basic" }
tardis = { version = "0.1.0-alpha4" }
poem-openapi = { version = "^1.3", optional = true }
sea-orm = { version = "^0.6", features = ["macros"], optional = true }

[dev-dependencies]
tokio = { version = "^1", features = ["time", "rt", "macros"] }

