version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.15.0-alpine
    volumes:
      - ./dashboard.yml:/usr/local/apisix-dashboard/conf/conf.yaml
    restart: always
    ports:
      - "9000:9000"
    networks:
      apisix:

  apisix:
    image: ghcr.io/ideal-world/bios-gateway:latest
    restart: always
    volumes:
      - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    depends_on:
      - etcd
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local

