[package]
name = "bios-basic"
version = "0.1.0"
authors = ["gudaoxuri <i@sunisle.org>"]
homepage = "https://bios.idealworld.group"
documentation = "https://bios.idealworld.group"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2021"
readme = "README.adoc"
publish = false

[profile.release]
lto = true
codegen-units = 1

[lib]
name = "bios_basic"
path = "src/lib.rs"

[features]
default = ["tardis", "tardis/crypto", "tardis/web-server", "tardis/web-client", "tardis/reldb", "poem-openapi", "sea-orm"]
with-mq = ["tardis/mq"]
with-cache = ["tardis/cache"]
sdk = ["tardis", "tardis/web-client", "poem-openapi"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
derive_more = { version = "^0" }
async-trait = { version = "^0" }
lazy_static = { version = "^1" }
itertools = { version = "^0" }


tardis = { path = "../../tardis", optional = true }
poem-openapi = { version = "^1.3", optional = true }
sea-orm = { version = "^0.7", features = ["macros"], optional = true }

[dev-dependencies]
tardis = { path = "../../tardis", features = ["test"] }

[[test]]
name = "test_rbum"
required-features = ["default", "with-mq", "with-cache"]