[package]
name = "bios-mw-schedule"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_mw_schedule"
path = "src/lib.rs"

[features]
default = ["spi-pg"]
spi-pg = ["tardis/reldb-postgres"]

[dependencies]
serde.workspace = true
lazy_static.workspace = true
# tokio-cron-scheduler = "*"
tardis = { workspace = true, features = ["reldb-postgres", "web-server"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default"] }
bios-sdk-invoke = { version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
    "spi_log", "spi_kv", "event"
], default-features = false }
tsuki-scheduler = { version = "0.1.3", features= ["cron", "tokio", "async-scheduler"]}
testcontainers-modules = { workspace = true, features = ["redis"] }

[dev-dependencies]
tardis = { workspace = true, features = ["test", "ws-client"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default", "test"] }
bios-spi-kv = { version = "0.2.0", path = "../../spi/spi-kv" }
bios-spi-log = { version = "0.2.0", path = "../../spi/spi-log" }
