[package]
name = "bios-reach"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_reach"
path = "src/lib.rs"

[features]
default = []
simple-client = []

[dependencies]
serde.workspace = true
lazy_static.workspace = true
tardis = { workspace = true, features = [
    "reldb-postgres",
    "web-server",
    "mail",
    "mq",
] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default"] }
bios-sdk-invoke = { version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
    "iam",
    "macro",
], default-features = false }
# simple-invoke-client-macro = { version = "0.2.0", path = "../../sdks/simple-invoke-client-macro" }
[dev-dependencies]
tardis = { workspace = true, features = ["test"] }

bios-basic = { version = "0.2.0", path = "../../basic", features = ["default", "test"] }

bios-reach = { path = "./", features = ["simple-client"] }
toml = "*"

bios-client-hwsms = { version = "0.2.0", path = "../../../frontend/clients/hwsms", features = ["reach"] }

testcontainers-modules = { workspace = true }
