[package]
name = "bios-example-framework-dummy-service"
version = "0.1.0"
authors = ["gudaoxuri"]
homepage = "https://bios.idealworld.group/framework"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
derive_more = "0.99"
log = "0.4"

bios-framework = { path = "../../../framework" }
actix-web = { version = "3", default-features = false, features = ["compress"] }
validator = { version = "0.12", features = ["derive"] }
actix-web-validator = "2"

rand = "0.8"
http = "0.2"
