[package]
name = "bios-example-framework-dummy-service"
version = "0.1.0"
authors = ["gudaoxuri"]
homepage = "https://bios.idealworld.group/framework"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
derive_more = "^0"
log = "^0"

bios-framework = { path = "../../../framework", features = ["web-client"] }
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["compress-gzip", "rustls"] }
validator = { version = "^0", features = ["derive"] }

rand = "0.8"
http = "0.2"
