[package]
name = "bios-spi-object"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_spi_object"
path = "src/lib.rs"

[features]
default = ["spi-s3"]
spi-s3 = ["tardis/os"]

[dependencies]
serde.workspace = true
itertools.workspace = true
tardis = { workspace = true, features = ["reldb-postgres", "web-server"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default"] }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default", "test"] }
