[package]
name = "bios-spi-search"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
name = "bios_spi_search"
path = "src/lib.rs"

[features]
default = ["spi-pg", "spi-es"]
spi-pg = ["tardis/reldb-postgres"]
spi-es = ["tardis/web-client"]
with-cn-tokenizer = []

[dependencies]
serde.workspace = true
itertools.workspace = true
tardis = { workspace = true, features = [
    "reldb-postgres",
    "web-server",
    "web-client",
    "openapi-rapidoc",
] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default"] }
strum = { workspace = true, features = ["derive"] }
pinyin = { version = "0.10" }
bios-sdk-invoke = { version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
    "event",
], default-features = false }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["default", "test"] }
testcontainers-modules = { workspace = true }
pinyin = { version = "0.10" }
