apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b6acecs1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"          # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 5

nginx_config:                     # config for render the template to generate nginx.conf
  #user: root                     # specifies the execution user of the worker process.
  # the "user" directive makes sense only if the master process runs with super-user privileges.
  # if you're not root user,the default is current user.
  error_log_level: warn

#plugin_attr:
#  opa:
#    host: ""