[package]
name = "bios-serv-all"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
serde.workspace = true
tardis = { workspace = true, features = [
    "web-server",
    "conf-remote",
    "reldb-mysql",
] }
bios-iam = { path = "../../core/iam" }
