[package]
name = "bios-example-framework-web-client"
version = "0.1.0"
authors = ["gudaoxuri"]
homepage = "https://bios.idealworld.group/framework"
repository = "https://github.com/ideal-world/bios"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
derive_more = "0.99"
log = "0.4"

bios-framework = { path = "../../../framework", default-features = false, features = ["rslog", "web_client"] }
awc = { version = "2", features = ["rustls"] }
actix-rt = "1"
