[package]
name = "bios-spi-serv-all"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
tardis = { workspace = true, features = [
    "web-server",
    "conf-remote",
] }
bios-basic = { version = "0.2.0", path = "../../basic", features = ["test"] }
bios-spi-cache = { version = "0.2.0", path = "../../spi/spi-cache" }
bios-spi-graph = { version = "0.2.0", path = "../../spi/spi-graph" }
bios-spi-kv = { version = "0.2.0", path = "../../spi/spi-kv" }
bios-spi-log = { version = "0.2.0", path = "../../spi/spi-log" }
bios-spi-object = { version = "0.2.0", path = "../../spi/spi-object" }
bios-spi-plugin = { version = "0.2.0", path = "../../spi/spi-plugin" }
bios-spi-reldb = { version = "0.2.0", path = "../../spi/spi-reldb" }
bios-spi-search = { version = "0.2.0", path = "../../spi/spi-search", features = ["default", "with-cn-tokenizer"] }
bios-spi-stats = { version = "0.2.0", path = "../../spi/spi-stats" }
bios-spi-conf = { version = "0.2.0", path = "../../spi/spi-conf" }
