[package]
name = "bios-sdk-invoke"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true
description.workspace = true

[lib]
name = "bios_sdk_invoke"
path = "src/lib.rs"

[features]
default = ["spi_kv", "spi_log", "spi_search", "spi_stats", "iam"]
spi_base = []
spi_kv = ["spi_base"]
spi_log = ["spi_base", "iam"]
spi_search = ["spi_base"]
spi_stats = ["spi_base"]
iam = []
event = ["asteroid-mq"]
macro = ["dep:simple-invoke-client-macro"]

[dependencies]
serde.workspace = true
lazy_static.workspace = true
itertools.workspace = true
tardis = { workspace = true, features = [
  "web-server",
  "web-client",
  "crypto",
  "ws-client",
] }
simple-invoke-client-macro = { version = "0.2.0", path = "../simple-invoke-client-macro", optional = true }
crossbeam = "0.8"
asteroid-mq = { workspace = true, features = ["cluster-k8s"], optional = true }
[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
simple-invoke-client-macro = { version = "0.2.0", path = "../simple-invoke-client-macro" }

[[test]]
name = "test_macros"
required-features = ["macro"]
