[package]
name = "bios-chat-core"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[lib]
name = "bios_chat_core"
path = "src/lib.rs"

[features]

[dependencies]
serde.workspace = true
tardis = { workspace = true, features = [
    "reldb",
    "web-server",
    "web-client",
    "os",
] }
bios-basic = { path = "../../../basic", features = ["default"] }
bios-chat-basic = { path = "../chat-basic" }

[dev-dependencies]
tardis = { workspace = true, features = ["test"] }
