[package]
name = "spacegate-plugins"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
serde.workspace = true
lazy_static.workspace = true
spacegate-shell = { workspace = true, features = [
  "cache",
  "k8s",
  "ext-redis",
  "ext-axum",
  "plugin-east-west-traffic-white-list",
] }

bios-sdk-invoke = { version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
  "spi_log",
], default-features = false }


jsonpath-rust = "0.3.1"
bios-auth = { version = "0.2.0", path = "../../supports/auth", default-features = false }
tardis = { workspace = true, features = ["web-client"] }
ipnet = "2.8.0"

http = { version = "1" }

[dev-dependencies]
pprof = { version = "0.12.1", features = ["flamegraph"] }
tardis = { workspace = true, features = ["test", "web-client"] }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
testcontainers-modules = { workspace = true, features = ["redis"] }

[[test]]
name = "export_schemas"
path = "tests/export_schemas.rs"
required-features = ["schema"]
