name: Publish gateway docker image

on:
  push:
    paths:
      - "core/gateway/Dockerfile"
      - "core/gateway/apisix/**"
      - ".github/workflows/gateway-docker.yml"

jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: core/gateway
          dockerfile: core/gateway/Dockerfile
          registry: ghcr.io
          image: bios-gateway
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
