name: Publish gateway docker image

on:
  push:
    paths:
      - "gateway/apisix/**"
      - ".github/workflows/gateway-docker.yml"

jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image to github
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: gateway
          dockerfile: gateway/apisix/Dockerfile
          registry: ghcr.io
          image: bios-gateway
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image to dockerhub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: gateway
          dockerfile: gateway/apisix/Dockerfile
          registry: docker.io
          image: ecfront/bios-gateway
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

