name: Publish all services docker image

on:
  push:
    paths:
      - "basic/**"
      - "core/iam/**"
      - "services/**"
      - ".github/workflows/service-all-docker.yml"

jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v1

      - name: Test1
        run: echo $(pwd)

      - name: Go to service directory
        run: cd ./services/bios-all

      - name: Test2
        run: echo $(pwd)

      - name: Test3
        run: echo $(ls -l)

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check with clippy
        run: cargo clippy --all-features

      - name: Build rust
        run: cargo build --release

      - name: Copy binary to workspace
        run: cp ../../target/release/bios-serv-all ./

      - name: Build and push Docker images
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: services/bios-all
          dockerfile: services/bios-all/Dockerfile
          registry: ghcr.io
          image: bios-serv-all
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Remove binary
        run: rm ./bios-serv-all