name: Release rust gateways docker image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt -p bios-spacegate --check

      - name: Check with clippy
        run: cargo clippy --all-features -p bios-spacegate

      - name: Build rust
        run: cargo build --release -p bios-spacegate

      - name: Copy binary to workspace
        run: cp ./target/release/bios-spacegate ./backend/services/spacegate/

      - name: Build and push Docker image to github
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: services/spacegate
          dockerfile: services/spacegate/Dockerfile
          registry: ghcr.io
          image: bios-spacegate
          tags: ${{ github.ref_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image to dockerhub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: backend/services/spacegate
          dockerfile: backend/services/spacegate/Dockerfile
          registry: docker.io
          image: ecfront/bios-spacegate
          tags: ${{ github.ref_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
